"""
phase3_pose_design.py
======================
AXON-R Phase 3 — protective pose design via biomechanical analysis in MuJoCo.

WHAT THIS SCRIPT ASSUMES ABOUT THE MODEL (read this first)
------------------------------------------------------------
g1_pendulum.xml has NO arms and NO head. The entire upper body is a 2-axis
reaction-mass pendulum (a 5kg "bob" 0.3m above the pelvis, collision-disabled
by default). There is therefore no way to measure a "hand" impact, and no
real arm-catch protective pose is physically representable on this rig.

This pipeline uses two impact proxies instead of the three the spec assumed:
  - PELVIS  : the existing pelvis collision geom (already contype/conaffinity
              enabled in the XML) -> stands in for hip/torso impact.
  - HEAD    : the pendulum bob, with contact ENABLED AT RUNTIME (in Python,
              not by editing the XML) -> stands in for head/upper-body
              impact, since it's the highest, heaviest point on the rig.
No XML edits are needed or shipped; g1_pendulum.xml is used as-is.

Report this limitation to your mentor explicitly before Phase 4 — the
damage comparison study should not silently claim a "hand" channel that
doesn't exist in the rig.

PIPELINE
--------
1. For each of the 15 Phase-1 scenarios, run the UNPROTECTED (baseline PD
   hold) fall at a magnitude that reliably falls, across a few
   timing/direction conditions -> establishes each scenario's natural
   time-to-ground-contact.
2. Optimize a 14-dim joint-angle pose (2 pendulum + 12 leg actuators) that,
   when commanded starting at (t_impact - LEAD_TIME_S), minimizes weighted
   peak impact force on the pelvis+head proxies, subject to:
     - joint limits (enforced as CMA-ES box bounds, so always reachable)
     - pose transition must complete within POSE_TRANSITION_BUDGET_S
   using CMA-ES (gradient-free — contact/impact events are discontinuous
   and non-differentiable, so no usable gradient exists through them).
3. Cross-evaluate every scenario's optimized pose against every OTHER
   scenario, to measure robustness to the ~25% fall-type misclassification
   rate from Phase 2.
4. Greedily merge scenarios whose poses are interchangeable with little
   performance loss, to compress 15 raw poses down into a final library of
   12-15 poses, each tagged with which scenario_ids / fall_directions it
   covers.
5. Write out pose_library.json with per-pose validation (joint-limit check,
   transition-time check, margin vs Phase 2 lead time).

Run:
    python phase3_pose_design.py --model g1_pendulum.xml --out phase3_out/
    python phase3_pose_design.py --model g1_pendulum.xml --quick   # smoke test

Requires: mujoco, numpy, cma  (pip install mujoco cma numpy)
Must be run from a directory where `generate_fall_dataset_final.py` (Phase 1)
is importable — this script reuses its scenario mechanisms directly so
Phase 3 falls are generated by the exact same physics as Phase 1/2.
"""
import argparse
import itertools
import json
import multiprocessing as mp
import os
import sys
import time
from dataclasses import dataclass, field, asdict

import numpy as np
import mujoco

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import generate_fall_dataset_final as p1  # reuse Phase 1 mechanisms verbatim


# ─────────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────────

LEAD_TIME_S = 0.30              # conservative trigger-to-impact budget to design
                                 # against (worst realistic case). Phase 2 achieved
                                 # median 396ms / mean 380ms -- see confirm_margin().
POSE_TRANSITION_BUDGET_S = 0.30 # mentor's spec: pose must land within 300ms
TRANSITION_TOL_RAD = 0.05       # "reached the pose" tolerance per joint (~2.9 deg)

W_HEAD = 2.0                    # weight on pendulum-bob (head-proxy) peak force
W_PELVIS = 1.0                  # weight on pelvis peak force
W_OTHER = 0.5                   # weight on any other non-foot body hitting the
                                 # ground (knee, hip-roll, etc). Lower than
                                 # pelvis/head since absorbing a fall through
                                 # the hip/thigh is genuinely less dangerous --
                                 # but NOT zero, so a pose can't escape scoring
                                 # entirely just by landing somewhere untracked.
TRANSITION_OVERRUN_PENALTY_PER_S = 500.0   # N-equivalent penalty per second over budget
INCOMPLETE_TRANSITION_PENALTY = 2000.0     # fixed penalty if pose never reached before impact

# Phase 1 stops a trial at the FIRST new ground contact (correct for
# detection labeling). For impact-force measurement that first contact is
# often a knee/hip touching down before the pelvis or head-proxy ever does
# -- so we deliberately keep simulating a short window past that first
# contact to actually capture the pelvis/head impact, instead of reading a
# false 0 N. Empirically (bob-height trace on push/forward): the pendulum
# bob doesn't reach the ground until ~1.3s post-disturbance, so 0.45s was
# far too short -- raised to 1.5s. This makes every trial ~3x more
# expensive; if a full run is too slow, profile per-scenario before cutting
# this back down rather than reverting it blindly.
POST_FALL_OBSERVATION_S = 1.5

# Conditions sampled per scenario during optimization (kept small for speed;
# widen for a final run). timing/jitter values are a subset of Phase 1's own
# grid so the sim is exercised the same way Phase 1 characterized it.
COND_TIMINGS = [0.0, 0.4]
COND_JITTERS = [-15, 15]

MERGE_TOLERANCE = 0.15   # allow <=15% score degradation when reusing one
                          # scenario's pose for another, to permit a merge
TARGET_LIBRARY_MIN = 12
TARGET_LIBRARY_MAX = 15


# ─────────────────────────────────────────────────────────────────
# MODEL INSTRUMENTATION (done at runtime, not via XML edits)
# ─────────────────────────────────────────────────────────────────

def load_instrumented_model(model_path):
    """Load g1_pendulum.xml unmodified, then enable contact on the pendulum
    bob geom(s) in Python so it can register ground impact as a head proxy."""
    m = mujoco.MjModel.from_xml_path(model_path)
    bob_body_id = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, "pendulum_bob")
    for gid in range(m.ngeom):
        if m.geom_bodyid[gid] == bob_body_id:
            m.geom_contype[gid] = 1
            m.geom_conaffinity[gid] = 1
    return m


# Several Phase 1 disturbance mechanisms mutate the MODEL itself, not just
# per-episode data: actuator_fault/asymmetric_gain multiply
# actuator_gainprm/biasprm IN PLACE every time they fire; floor_tilt_* sets
# opt.gravity; low_friction sets geom_friction. Phase 1 got away with this
# because it loads a brand-new MjModel per trial. Phase 3 reuses ONE model
# instance across thousands of trials for speed, so without an explicit
# reset these mutations leak and compound across every later trial and
# scenario. Snapshot the mutable fields once, restore them before every trial.
_MUTABLE_MODEL_FIELDS = ["actuator_gainprm", "actuator_biasprm", "geom_friction",
                          "geom_contype", "geom_conaffinity"]


def snapshot_model_state(model):
    snap = {name: getattr(model, name).copy() for name in _MUTABLE_MODEL_FIELDS}
    snap["gravity"] = model.opt.gravity.copy()
    return snap


def restore_model_state(model, snapshot):
    for name in _MUTABLE_MODEL_FIELDS:
        getattr(model, name)[:] = snapshot[name]
    model.opt.gravity[:] = snapshot["gravity"]


def impact_body_ids(model):
    pelvis_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "pelvis")
    bob_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "pendulum_bob")
    return {"pelvis": pelvis_id, "head": bob_id}


def contact_peak_forces(model, data, ground_id, body_ids, foot_geom_ids):
    """Peak resultant contact force this step, per tracked body (pelvis,
    head), counting ONLY contacts against the ground geom (environmental
    impact) -- contacts between the robot's own links are ignored so
    folded/self-contact doesn't get mistaken for an impact.

    Also tracks `other`: peak force from any NON-FOOT body contacting the
    ground that isn't pelvis or head (e.g. a knee or hip-roll link). Normal
    standing foot-ground contact (the robot's own body weight resting on
    its feet, every single step of every trial) is excluded via
    `foot_geom_ids` -- without this exclusion `other` picks up ordinary
    standing/walking forces on EVERY trial, which would corrupt every score,
    not just the intended edge case.

    This channel exists specifically so a pose that dumps the fall onto an
    untracked body part reads as a mitigated-but-real impact, not a free 0
    -- see the reward-hacking case found in actuator_fault, where an
    aggressive pose collapsed the robot onto its own knee/hip with zero
    disturbance applied at all, and scored a perfect 0 because only
    pelvis/head were tracked."""
    peaks = {k: 0.0 for k in body_ids}
    peaks["other"] = 0.0
    for c in range(data.ncon):
        con = data.contact[c]
        g1, g2 = con.geom1, con.geom2
        if ground_id not in (g1, g2):
            continue
        other_g = g2 if g1 == ground_id else g1
        if other_g in foot_geom_ids:
            continue
        other_body = model.geom_bodyid[other_g]
        force6 = np.zeros(6)
        mujoco.mj_contactForce(model, data, c, force6)
        mag = float(np.linalg.norm(force6[:3]))
        matched = False
        for name, bid in body_ids.items():
            if other_body == bid:
                if mag > peaks[name]:
                    peaks[name] = mag
                matched = True
        if not matched and mag > peaks["other"]:
            peaks["other"] = mag
    return peaks


# ─────────────────────────────────────────────────────────────────
# UNPROTECTED BASELINE (find natural time-to-impact per scenario)
# ─────────────────────────────────────────────────────────────────

def fall_magnitude(fn_name):
    """Magnitude near the top of Phase 1's calibrated range -> reliable fall.
    (No labels.csv is needed for this: the ranges live in Phase 1's own
    MAGNITUDE_RANGES table, which was uploaded and is authoritative.)"""
    lo, hi = p1.MAGNITUDE_RANGES[fn_name]
    return lo + 0.85 * (hi - lo)


def baseline_time_to_impact(model_path, scenario, timing_phase_s, jitter_deg):
    """Run the exact Phase-1 unprotected rollout (no pose intervention) far
    enough to find ground-truth time_to_ground_contact for this condition."""
    scen_id, category, fn_name, nominal_dir = scenario
    direction = ((nominal_dir + jitter_deg) % 360) if nominal_dir is not None else None
    mag = fall_magnitude(fn_name)
    label = p1.run_trial(model_path, scenario, mag, direction, timing_phase_s,
                          seed=1234, trial_id="phase3_baseline",
                          log_dir="/tmp")
    return label, mag, direction


# ─────────────────────────────────────────────────────────────────
# PROTECTED ROLLOUT (the thing we optimize)
# ─────────────────────────────────────────────────────────────────

@dataclass
class TrialResult:
    peak_force_pelvis: float
    peak_force_head: float
    peak_force_other: float           # any non-foot, non-pelvis, non-head body
                                       # hitting the ground -- e.g. a knee/hip
                                       # (see contact_peak_forces docstring)
    transition_time_s: float          # None-like via -1.0 if never completed
    transition_complete: bool
    time_to_impact_s: float           # -1.0 if the UNPROTECTED baseline never
                                       # fell within the observation window --
                                       # in that case the pose is never
                                       # triggered at all (see below), so
                                       # this condition can't be gamed
    fell: bool
    no_natural_fall: bool             # True if baseline never falls unprotected
                                       # -> pose was not applied; excluded from
                                       # meaningful optimization signal


def run_protected_trial(model, scenario, magnitude, direction_deg, timing_phase_s,
                         pose_ctrl, trigger_lead_s, impact_ids, snapshot):
    """Re-run the same disturbance mechanism as Phase 1, but from
    (t_impact_estimate - trigger_lead_s) onward, command `pose_ctrl` instead
    of holding `stand`. `model` must already be mj.MjModel instrumented via
    load_instrumented_model(); a fresh MjData is created per trial. `snapshot`
    (from snapshot_model_state) is restored first so mutations left over from
    a PREVIOUS trial (actuator_fault gains, tilted gravity, etc.) can't leak
    in -- see the big comment above snapshot_model_state for why this matters."""
    restore_model_state(model, snapshot)
    scen_id, category, fn_name, nominal_dir = scenario
    d = mujoco.MjData(model)
    mujoco.mj_resetDataKeyframe(model, d, 0)
    stand_ctrl = model.key_ctrl[0].copy()
    d.ctrl[:] = stand_ctrl

    ground_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, "ground")
    foot_ids = p1.get_foot_geom_ids(model)

    dt = model.opt.timestep
    settle_steps = int(p1.SETTLE_TIME / dt)
    for _ in range(settle_steps):
        d.ctrl[:] = stand_ctrl
        mujoco.mj_step(model, d)
    baseline_contacts = p1.snapshot_contacts(model, d, ground_id)

    # First pass (no pose) to find this condition's natural time-to-impact,
    # so we know when to trigger. This probe pass itself invokes the
    # disturbance mechanism and can mutate `model` (actuator gains, gravity,
    # ...), so restore pristine state again right after it, before the real
    # stepping loop below runs the SAME mechanism for real.
    t_impact = _find_time_to_impact(model, scenario, magnitude, direction_deg,
                                     timing_phase_s, snapshot)
    restore_model_state(model, snapshot)
    # If the UNPROTECTED baseline never falls within the observation window,
    # there is no real fall to protect against for this condition -- send
    # the trigger to "never" (past MAX_EPISODE_TIME) so the pose is NOT
    # applied at all, rather than falling back to an immediate trigger.
    # The old fallback (trigger at t=0) is what let the optimizer discover
    # that an aggressive pose applied cold, with no disturbance active yet,
    # could self-collapse the robot onto an untracked body part and score a
    # free 0 -- confirmed directly: the SAME pose produces the SAME collapse
    # with the disturbance function entirely removed. See the comment above
    # the `no_natural_fall` field in TrialResult.
    no_natural_fall = t_impact is None
    trigger_t_rel = max(0.0, t_impact - trigger_lead_s) if not no_natural_fall else float("inf")

    builder = p1.SCENARIO_BUILDERS[fn_name]
    disturb_fn = builder(model, magnitude, direction=direction_deg)

    max_steps = int(p1.MAX_EPISODE_TIME / dt)
    timing_steps = int(timing_phase_s / dt)
    stable_window_steps = int(p1.STABLE_WINDOW / dt)

    peak = {"pelvis": 0.0, "head": 0.0, "other": 0.0}
    fell, stable = False, False
    stable_counter = 0
    step = 0
    pose_ctrl = np.asarray(pose_ctrl)
    n_act = pose_ctrl.shape[0]
    transition_time_s = -1.0
    transition_complete = False
    trigger_fired = False
    trigger_step = None
    fell_step = None

    while step < max_steps:
        t_rel = (step - timing_steps) * dt
        if step >= timing_steps and max(t_rel, 0.0) >= trigger_t_rel:
            d.ctrl[:n_act] = pose_ctrl
            if not trigger_fired:
                trigger_fired = True
                trigger_step = step
        else:
            d.ctrl[:] = stand_ctrl

        if step >= timing_steps:
            disturb_fn(model, d, max(t_rel, 0.0))  # may override some ctrl entries

        mujoco.mj_step(model, d)
        step += 1

        forces = contact_peak_forces(model, d, ground_id, impact_ids, foot_ids)
        peak["pelvis"] = max(peak["pelvis"], forces["pelvis"])
        peak["head"] = max(peak["head"], forces["head"])
        peak["other"] = max(peak["other"], forces["other"])

        if trigger_fired and not transition_complete:
            err = np.abs(d.qpos[7:7 + n_act] - pose_ctrl)  # qpos[7:] = actuated joints
            if np.all(err < TRANSITION_TOL_RAD):
                transition_complete = True
                transition_time_s = (step - trigger_step) * dt

        current_contacts = p1.snapshot_contacts(model, d, ground_id)
        new_bad_contacts = (current_contacts - baseline_contacts) - foot_ids
        if new_bad_contacts and not fell:
            fell = True
            fell_step = step
        if fell and (step - fell_step) * dt >= POST_FALL_OBSERVATION_S:
            break

        if step >= timing_steps:
            pelvis_z = d.qpos[2]
            gyro_norm = np.linalg.norm(d.qvel[3:6])
            stable_now = (pelvis_z > p1.STABLE_PELVIS_Z_MIN and gyro_norm < p1.STABLE_ANGVEL_MAX)
            stable_counter = stable_counter + 1 if stable_now else 0
            if stable_counter >= stable_window_steps:
                stable = True
                break

    return TrialResult(
        peak_force_pelvis=peak["pelvis"], peak_force_head=peak["head"],
        peak_force_other=peak["other"],
        transition_time_s=transition_time_s, transition_complete=transition_complete,
        time_to_impact_s=t_impact if t_impact is not None else -1.0, fell=fell,
        no_natural_fall=no_natural_fall,
    )


def _find_time_to_impact(model, scenario, magnitude, direction_deg, timing_phase_s, snapshot):
    """One quick unprotected pass (fresh MjData, same model) to get this
    condition's natural time_to_ground_contact, used only to time the trigger.
    Restores pristine model state first -- this probe pass mutates `model`
    itself for several scenario types (see snapshot_model_state), and the
    caller is responsible for restoring again afterward before it does its
    own real stepping on the same model."""
    restore_model_state(model, snapshot)
    scen_id, category, fn_name, nominal_dir = scenario
    d = mujoco.MjData(model)
    mujoco.mj_resetDataKeyframe(model, d, 0)
    stand_ctrl = model.key_ctrl[0].copy()
    d.ctrl[:] = stand_ctrl
    ground_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, "ground")
    foot_ids = p1.get_foot_geom_ids(model)
    dt = model.opt.timestep
    settle_steps = int(p1.SETTLE_TIME / dt)
    for _ in range(settle_steps):
        d.ctrl[:] = stand_ctrl
        mujoco.mj_step(model, d)
    baseline_contacts = p1.snapshot_contacts(model, d, ground_id)
    builder = p1.SCENARIO_BUILDERS[fn_name]
    disturb_fn = builder(model, magnitude, direction=direction_deg)
    max_steps = int(p1.MAX_EPISODE_TIME / dt)
    timing_steps = int(timing_phase_s / dt)
    step = 0
    while step < max_steps:
        d.ctrl[:] = stand_ctrl
        t_rel = (step - timing_steps) * dt
        if step >= timing_steps:
            disturb_fn(model, d, max(t_rel, 0.0))
        mujoco.mj_step(model, d)
        step += 1
        current_contacts = p1.snapshot_contacts(model, d, ground_id)
        new_bad = (current_contacts - baseline_contacts) - foot_ids
        if new_bad:
            return step * dt - timing_phase_s
    return None  # never fell in this pass -- caller should raise magnitude


# ─────────────────────────────────────────────────────────────────
# MULTIPROCESSING (CPU-parallel; there is no GPU path for plain MuJoCo --
# see the module docstring notes on this. What IS parallelizable: every
# candidate pose within a single CMA-ES generation is scored completely
# independently, so we hand popsize candidates to a worker pool instead of
# evaluating them one at a time. Each worker process loads its OWN model
# instance once (via _worker_init) rather than pickling a shared MjModel
# across processes -- this is also naturally immune to the model-mutation
# contamination bug fixed earlier, since separate processes can't share
# mutable state at all.
# ─────────────────────────────────────────────────────────────────

_worker_model = None
_worker_snapshot = None


def _worker_init(model_path):
    global _worker_model, _worker_snapshot
    _worker_model = load_instrumented_model(model_path)
    _worker_snapshot = snapshot_model_state(_worker_model)


def _worker_score_task(task):
    scenario, pose_ctrl, conditions, lead_time_s = task
    impact_ids = impact_body_ids(_worker_model)
    return score_pose(_worker_model, scenario, pose_ctrl, conditions, impact_ids,
                       lead_time_s, _worker_snapshot)


# ─────────────────────────────────────────────────────────────────
# OPTIMIZATION (CMA-ES, gradient-free)
# ─────────────────────────────────────────────────────────────────

def actuator_bounds(model):
    lo = model.actuator_ctrlrange[:, 0].copy()
    hi = model.actuator_ctrlrange[:, 1].copy()
    return lo, hi


def build_conditions(scenario):
    scen_id, category, fn_name, nominal_dir = scenario
    mag = fall_magnitude(fn_name)
    conds = []
    for timing in COND_TIMINGS:
        for jitter in COND_JITTERS:
            direction = ((nominal_dir + jitter) % 360) if nominal_dir is not None else None
            conds.append((mag, direction, timing))
    return conds


def score_pose(model, scenario, pose_ctrl, conditions, impact_ids, lead_time_s, snapshot):
    total = 0.0
    counted = 0
    diagnostics = []
    for mag, direction, timing in conditions:
        r = run_protected_trial(model, scenario, mag, direction, timing,
                                 pose_ctrl, lead_time_s, impact_ids, snapshot)
        diagnostics.append(r)
        if r.no_natural_fall:
            # Baseline never fell within the observation window at this
            # magnitude/timing -- the pose was never triggered (see
            # run_protected_trial), so there is nothing real to score.
            # Excluded from the average rather than defaulted to 0: a
            # constant 0 here is exactly the loophole that previously let
            # an aggressive pose "win" a condition by self-colliding, with
            # no disturbance ever active, purely because untriggered ==
            # untracked == free.
            continue
        s = (W_HEAD * r.peak_force_head + W_PELVIS * r.peak_force_pelvis
             + W_OTHER * r.peak_force_other)
        if not r.transition_complete:
            s += INCOMPLETE_TRANSITION_PENALTY
        else:
            overrun = max(0.0, r.transition_time_s - POSE_TRANSITION_BUDGET_S)
            s += TRANSITION_OVERRUN_PENALTY_PER_S * overrun
        total += s
        counted += 1
    if counted == 0:
        # Every condition failed to produce a natural fall at this
        # magnitude -- there is nothing for this pose search to optimize.
        # Surface this loudly (NaN) instead of silently returning a
        # deceptively perfect 0; the caller must recalibrate magnitude for
        # this scenario rather than trust a pose from here.
        return float("nan"), diagnostics
    return total / counted, diagnostics


def optimize_pose_for_scenario(model, scenario, lead_time_s, popsize, maxiter, snapshot,
                                seed=0, pool=None):
    """`pool`: an optional multiprocessing.Pool (see main()/_worker_init). When
    given, every candidate in a CMA-ES generation is scored in parallel across
    worker processes instead of one at a time in this process."""
    import cma
    scen_id, category, fn_name, nominal_dir = scenario
    lo, hi = actuator_bounds(model)
    x0 = model.key_ctrl[0].copy()   # start the search at the 'stand' pose
    sigma0 = 0.3
    conditions = build_conditions(scenario)
    impact_ids = impact_body_ids(model)

    # Pre-check: if the UNPROTECTED baseline never falls for ANY tested
    # condition at this scenario's calibrated magnitude, no candidate pose
    # can ever produce a real score (the pose is only ever triggered off a
    # confirmed natural fall -- see run_protected_trial). Every candidate
    # would return NaN and best_score would never get set, so check this
    # up front with the cheap 'stand' pose rather than burning the whole
    # CMA-ES budget on a search that cannot possibly succeed.
    probe_score, probe_diag = score_pose(model, scenario, x0, conditions, impact_ids,
                                          lead_time_s, snapshot)
    if probe_score != probe_score:  # NaN check without importing math
        print(f"  [WARN] scenario {scen_id} ({fn_name}): baseline never falls "
              f"within the observation window for ANY tested condition at the "
              f"current magnitude -- skipping optimization. Recalibrate "
              f"fall_magnitude()/MAGNITUDE_RANGES for this scenario before "
              f"trusting anything downstream of it.")
        return {
            "scenario_id": scen_id, "scenario_fn": fn_name, "category": category,
            "pose": x0.tolist(), "score": float("nan"), "valid": False,
            "diagnostics": [asdict(d) for d in probe_diag],
        }

    es = cma.CMAEvolutionStrategy(
        x0, sigma0,
        {"bounds": [lo.tolist(), hi.tolist()], "popsize": popsize,
         "maxiter": maxiter, "seed": seed, "verbose": -9},
    )
    best_score, best_diag, best_x = probe_score, probe_diag, x0
    while not es.stop():
        candidates = es.ask()
        if pool is not None:
            tasks = [(scenario, np.array(x), conditions, lead_time_s) for x in candidates]
            results = pool.map(_worker_score_task, tasks)
        else:
            results = [score_pose(model, scenario, np.array(x), conditions, impact_ids,
                                   lead_time_s, snapshot) for x in candidates]
        fitnesses = []
        for x, (s, diag) in zip(candidates, results):
            # NaN candidates (a subset of conditions loses its natural fall
            # under this particular pose/timing combo) must not be handed to
            # CMA-ES as fitness -- replace with a large-but-finite penalty so
            # the search steers away from them instead of crashing or being
            # silently ignored.
            fitnesses.append(s if s == s else 1e6)
            if s == s and s < best_score:
                best_score, best_diag, best_x = s, diag, np.array(x)
        es.tell(candidates, fitnesses)

    return {
        "scenario_id": scen_id, "scenario_fn": fn_name, "category": category,
        "pose": best_x.tolist(), "score": float(best_score), "valid": True,
        "diagnostics": [asdict(d) for d in best_diag],
    }


# ─────────────────────────────────────────────────────────────────
# CROSS-EVALUATION + LIBRARY MERGING
# ─────────────────────────────────────────────────────────────────

def cross_evaluate(model, scenarios, raw_results, lead_time_s, snapshot, pool=None):
    """score[i][j] = mean score when scenario_i's pose is applied to
    scenario_j's own conditions. Diagonal = each scenario's own optimum.
    Every (i, j) cell is independent -- parallelized across `pool` the same
    way optimize_pose_for_scenario parallelizes CMA-ES candidates."""
    impact_ids = impact_body_ids(model)
    n = len(scenarios)
    cells = [(i, j) for j in range(n) for i in range(n)]
    conds_by_j = {j: build_conditions(scenarios[j]) for j in range(n)}

    if pool is not None:
        tasks = [(scenarios[j], np.array(raw_results[i]["pose"]), conds_by_j[j], lead_time_s)
                 for i, j in cells]
        results = pool.map(_worker_score_task, tasks)
    else:
        results = [score_pose(model, scenarios[j], np.array(raw_results[i]["pose"]),
                               conds_by_j[j], impact_ids, lead_time_s, snapshot)
                   for i, j in cells]

    matrix = np.zeros((n, n))
    for (i, j), (s, _) in zip(cells, results):
        matrix[i, j] = s
    return matrix


def merge_library(scenarios, raw_results, cross_matrix):
    """Greedily merge scenario i into scenario j (drop i's own pose, cover
    it with j's) whenever the cross-degradation is within MERGE_TOLERANCE of
    each scenario's own optimum, stopping once the library is within
    [TARGET_LIBRARY_MIN, TARGET_LIBRARY_MAX] poses."""
    n = len(scenarios)
    own = np.diag(cross_matrix)
    groups = {i: {i} for i in range(n)}   # pose_id -> set of scenario indices it covers
    representative = {i: i for i in range(n)}  # scenario idx -> current pose_id

    pairs = []
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            degradation = (cross_matrix[i, j] - own[j]) / max(own[j], 1e-6)
            pairs.append((degradation, i, j))
    pairs.sort(key=lambda t: t[0])

    for degradation, i, j in pairs:
        if len(groups) <= TARGET_LIBRARY_MIN:
            break
        if degradation > MERGE_TOLERANCE:
            break
        pi, pj = representative[i], representative[j]
        if pi == pj:
            continue
        # merge scenario j's group into i's pose, provided i's pose still
        # meets tolerance for every scenario already in i's group (checked
        # via cross_matrix, since it's precomputed for all i,j pairs)
        ok = all((cross_matrix[i, k] - own[k]) / max(own[k], 1e-6) <= MERGE_TOLERANCE
                 for k in groups[pj] | {j})
        if not ok:
            continue
        groups[pi] |= groups.pop(pj)
        for k in groups[pi]:
            representative[k] = pi
        if len(groups) <= TARGET_LIBRARY_MAX:
            pass  # keep trying cheap merges until MIN, but MAX is already satisfied

    return groups, representative


# ─────────────────────────────────────────────────────────────────
# MARGIN CONFIRMATION (mentor's explicit ask)
# ─────────────────────────────────────────────────────────────────

def confirm_margin(phase2_median_lead_ms=396.0, phase2_mean_lead_ms=380.0):
    budget_ms = POSE_TRANSITION_BUDGET_S * 1000.0
    margin_median = phase2_median_lead_ms - budget_ms
    margin_mean = phase2_mean_lead_ms - budget_ms
    print(f"[margin check] pose transition budget = {budget_ms:.0f} ms")
    print(f"  vs Phase 2 median lead time {phase2_median_lead_ms:.0f} ms "
          f"-> {margin_median:+.0f} ms margin for compute/comms overhead")
    print(f"  vs Phase 2 mean lead time   {phase2_mean_lead_ms:.0f} ms "
          f"-> {margin_mean:+.0f} ms margin")
    if margin_mean < 0:
        print("  [WARN] even the MEAN lead time does not clear the transition "
              "budget -- tighten the pose search's transition penalty or "
              "revisit debouncing latency before Phase 5.")
    return margin_median, margin_mean


# ─────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=r"C:\Users\Asyncronix\Downloads\Asyncronix_Intern\g1-pendulum-balance\unitree_g1\g1_pendulum.xml")
    ap.add_argument("--out", default="phase3_out_workers")
    ap.add_argument("--popsize", type=int, default=16)
    ap.add_argument("--maxiter", type=int, default=60)
    ap.add_argument("--lead-time", type=float, default=LEAD_TIME_S)
    ap.add_argument("--quick", action="store_true",
                     help="tiny popsize/maxiter/1 scenario, for a smoke test")
    ap.add_argument("--workers", type=int, default=1,
                     help="CPU worker processes for parallel pose evaluation "
                          "(there is no GPU path for plain MuJoCo -- see module "
                          "docstring). 1 = serial, unchanged behavior. Try "
                          "os.cpu_count()-1 on your machine; each worker loads "
                          "its own model copy, so watch RAM with very high counts.")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    confirm_margin()

    model = load_instrumented_model(args.model)
    snapshot = snapshot_model_state(model)  # pristine reference, restored before every trial
    scenarios = p1.SCENARIOS if not args.quick else p1.SCENARIOS[:1]
    popsize = 4 if args.quick else args.popsize
    maxiter = 2 if args.quick else args.maxiter

    pool = None
    if args.workers > 1:
        model_abspath = os.path.abspath(args.model)
        pool = mp.Pool(processes=args.workers, initializer=_worker_init,
                        initargs=(model_abspath,))
        print(f"Started a pool of {args.workers} worker processes "
              f"(CPU-parallel, not GPU).")

    print(f"\nOptimizing {len(scenarios)} scenario poses "
          f"(popsize={popsize}, maxiter={maxiter}, lead_time={args.lead_time}s)...")
    raw_results = []
    try:
        for scenario in scenarios:
            t0 = time.time()
            res = optimize_pose_for_scenario(model, scenario, args.lead_time, popsize, maxiter,
                                              snapshot, pool=pool)
            print(f"  scenario {res['scenario_id']:>2} ({res['scenario_fn']:<18}) "
                  f"score={res['score']:.1f}  [{time.time()-t0:.1f}s]")
            raw_results.append(res)

        invalid = [r for r in raw_results if not r.get("valid", True)]
        if invalid:
            print(f"\n[WARN] {len(invalid)} scenario(s) never fall unprotected within the "
                  f"observation window at their current calibrated magnitude, so no pose "
                  f"could be optimized for them: "
                  + ", ".join(f"{r['scenario_id']} ({r['scenario_fn']})" for r in invalid))
            print("  These are EXCLUDED from the pose library below, not merged with a "
                  "placeholder. Recalibrate fall_magnitude()/MAGNITUDE_RANGES (or widen the "
                  "probe window past MAX_EPISODE_TIME) for these scenarios and re-run before "
                  "considering Phase 3 complete for them.")

        valid_indices = [i for i, r in enumerate(raw_results) if r.get("valid", True)]
        scenarios_v = [scenarios[i] for i in valid_indices]
        raw_results_v = [raw_results[i] for i in valid_indices]

        if len(scenarios_v) > 1:
            print("\nCross-evaluating pose robustness across scenarios...")
            cross_matrix = cross_evaluate(model, scenarios_v, raw_results_v, args.lead_time,
                                           snapshot, pool=pool)
            groups, representative = merge_library(scenarios_v, raw_results_v, cross_matrix)
            print(f"Merged {len(scenarios_v)} scenario-specific poses into "
                  f"{len(groups)} library poses.")
        elif len(scenarios_v) == 1:
            cross_matrix = None
            groups = {0: {0}}
            representative = {0: 0}
        else:
            groups = {}
    finally:
        if pool is not None:
            pool.close()
            pool.join()

    library = []
    for pose_id, covered in groups.items():
        covered_scenarios = [scenarios_v[k] for k in covered]
        directions = sorted({
            _direction_label(s) for s in covered_scenarios
        })
        library.append({
            "pose_id": pose_id,
            "pose": raw_results_v[pose_id]["pose"],
            "covers_scenario_ids": [scenarios_v[k][0] for k in covered],
            "covers_scenario_fns": [scenarios_v[k][2] for k in covered],
            "fall_directions": directions,
            "own_score": raw_results_v[pose_id]["score"],
            "diagnostics": raw_results_v[pose_id]["diagnostics"],
        })

    out_path = os.path.join(args.out, "pose_library.json")
    with open(out_path, "w") as f:
        json.dump({
            "lead_time_s_used_for_design": args.lead_time,
            "pose_transition_budget_s": POSE_TRANSITION_BUDGET_S,
            "impact_proxies": {
                "pelvis": "pelvis collision geom (existing)",
                "head": "pendulum bob, contact enabled at runtime",
                "hands": "NOT MODELED -- rig has no arms",
                "other": "any other non-foot body (e.g. knee/hip) -- weighted "
                         "lower than pelvis/head, but not free",
            },
            "excluded_scenarios_needing_recalibration": [
                {"scenario_id": r["scenario_id"], "scenario_fn": r["scenario_fn"]}
                for r in invalid
            ],
            "n_poses": len(library),
            "poses": library,
        }, f, indent=2)
    print(f"\nWrote {len(library)} poses to {out_path}")


def _direction_label(scenario):
    scen_id, category, fn_name, nominal_dir = scenario
    if nominal_dir is None:
        return category  # non-directional mechanisms (surface/actuator/trip)
    table = {0: "forward", 180: "backward", 90: "left", 270: "right",
             45: "forward-left", 315: "forward-right"}
    return table.get(nominal_dir, f"{nominal_dir}deg")


if __name__ == "__main__":
    main()
